// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/readonme/open-studio/dal/model"
)

func newBotPlugin(db *gorm.DB, opts ...gen.DOOption) botPlugin {
	_botPlugin := botPlugin{}

	_botPlugin.botPluginDo.UseDB(db, opts...)
	_botPlugin.botPluginDo.UseModel(&model.BotPlugin{})

	tableName := _botPlugin.botPluginDo.TableName()
	_botPlugin.ALL = field.NewAsterisk(tableName)
	_botPlugin.ID = field.NewInt64(tableName, "id")
	_botPlugin.BotID = field.NewInt64(tableName, "bot_id")
	_botPlugin.PluginID = field.NewInt64(tableName, "plugin_id")
	_botPlugin.CreatedAt = field.NewTime(tableName, "created_at")

	_botPlugin.fillFieldMap()

	return _botPlugin
}

type botPlugin struct {
	botPluginDo botPluginDo

	ALL       field.Asterisk
	ID        field.Int64
	BotID     field.Int64
	PluginID  field.Int64
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (b botPlugin) Table(newTableName string) *botPlugin {
	b.botPluginDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b botPlugin) As(alias string) *botPlugin {
	b.botPluginDo.DO = *(b.botPluginDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *botPlugin) updateTableName(table string) *botPlugin {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.BotID = field.NewInt64(table, "bot_id")
	b.PluginID = field.NewInt64(table, "plugin_id")
	b.CreatedAt = field.NewTime(table, "created_at")

	b.fillFieldMap()

	return b
}

func (b *botPlugin) WithContext(ctx context.Context) *botPluginDo {
	return b.botPluginDo.WithContext(ctx)
}

func (b botPlugin) TableName() string { return b.botPluginDo.TableName() }

func (b botPlugin) Alias() string { return b.botPluginDo.Alias() }

func (b botPlugin) Columns(cols ...field.Expr) gen.Columns { return b.botPluginDo.Columns(cols...) }

func (b *botPlugin) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *botPlugin) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 4)
	b.fieldMap["id"] = b.ID
	b.fieldMap["bot_id"] = b.BotID
	b.fieldMap["plugin_id"] = b.PluginID
	b.fieldMap["created_at"] = b.CreatedAt
}

func (b botPlugin) clone(db *gorm.DB) botPlugin {
	b.botPluginDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b botPlugin) replaceDB(db *gorm.DB) botPlugin {
	b.botPluginDo.ReplaceDB(db)
	return b
}

type botPluginDo struct{ gen.DO }

func (b botPluginDo) Debug() *botPluginDo {
	return b.withDO(b.DO.Debug())
}

func (b botPluginDo) WithContext(ctx context.Context) *botPluginDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b botPluginDo) ReadDB() *botPluginDo {
	return b.Clauses(dbresolver.Read)
}

func (b botPluginDo) WriteDB() *botPluginDo {
	return b.Clauses(dbresolver.Write)
}

func (b botPluginDo) Session(config *gorm.Session) *botPluginDo {
	return b.withDO(b.DO.Session(config))
}

func (b botPluginDo) Clauses(conds ...clause.Expression) *botPluginDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b botPluginDo) Returning(value interface{}, columns ...string) *botPluginDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b botPluginDo) Not(conds ...gen.Condition) *botPluginDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b botPluginDo) Or(conds ...gen.Condition) *botPluginDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b botPluginDo) Select(conds ...field.Expr) *botPluginDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b botPluginDo) Where(conds ...gen.Condition) *botPluginDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b botPluginDo) Order(conds ...field.Expr) *botPluginDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b botPluginDo) Distinct(cols ...field.Expr) *botPluginDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b botPluginDo) Omit(cols ...field.Expr) *botPluginDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b botPluginDo) Join(table schema.Tabler, on ...field.Expr) *botPluginDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b botPluginDo) LeftJoin(table schema.Tabler, on ...field.Expr) *botPluginDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b botPluginDo) RightJoin(table schema.Tabler, on ...field.Expr) *botPluginDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b botPluginDo) Group(cols ...field.Expr) *botPluginDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b botPluginDo) Having(conds ...gen.Condition) *botPluginDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b botPluginDo) Limit(limit int) *botPluginDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b botPluginDo) Offset(offset int) *botPluginDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b botPluginDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *botPluginDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b botPluginDo) Unscoped() *botPluginDo {
	return b.withDO(b.DO.Unscoped())
}

func (b botPluginDo) Create(values ...*model.BotPlugin) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b botPluginDo) CreateInBatches(values []*model.BotPlugin, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b botPluginDo) Save(values ...*model.BotPlugin) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b botPluginDo) First() (*model.BotPlugin, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BotPlugin), nil
	}
}

func (b botPluginDo) Take() (*model.BotPlugin, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BotPlugin), nil
	}
}

func (b botPluginDo) Last() (*model.BotPlugin, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BotPlugin), nil
	}
}

func (b botPluginDo) Find() ([]*model.BotPlugin, error) {
	result, err := b.DO.Find()
	return result.([]*model.BotPlugin), err
}

func (b botPluginDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BotPlugin, err error) {
	buf := make([]*model.BotPlugin, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b botPluginDo) FindInBatches(result *[]*model.BotPlugin, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b botPluginDo) Attrs(attrs ...field.AssignExpr) *botPluginDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b botPluginDo) Assign(attrs ...field.AssignExpr) *botPluginDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b botPluginDo) Joins(fields ...field.RelationField) *botPluginDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b botPluginDo) Preload(fields ...field.RelationField) *botPluginDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b botPluginDo) FirstOrInit() (*model.BotPlugin, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BotPlugin), nil
	}
}

func (b botPluginDo) FirstOrCreate() (*model.BotPlugin, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BotPlugin), nil
	}
}

func (b botPluginDo) FindByPage(offset int, limit int) (result []*model.BotPlugin, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b botPluginDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b botPluginDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b botPluginDo) Delete(models ...*model.BotPlugin) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *botPluginDo) withDO(do gen.Dao) *botPluginDo {
	b.DO = *do.(*gen.DO)
	return b
}
