// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBotDraft = "bot_drafts"

// BotDraft mapped from table <bot_drafts>
type BotDraft struct {
	ID                  int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BotID               int64     `gorm:"column:bot_id;not null" json:"bot_id"`
	CreatorID           int64     `gorm:"column:creator_id;not null" json:"creator_id"`
	Status              int32     `gorm:"column:status;comment:0-default 1-publish" json:"status"` // 0-default 1-publish
	Prompt              string    `gorm:"column:prompt" json:"prompt"`
	Plugins             string    `gorm:"column:plugins" json:"plugins"`
	WelcomeMsg          string    `gorm:"column:welcome_msg" json:"welcome_msg"`
	GuideInfo           string    `gorm:"column:guide_info" json:"guide_info"`
	ModelSettings       string    `gorm:"column:model_settings" json:"model_settings"`
	DebugConversationID int64     `gorm:"column:debug_conversation_id" json:"debug_conversation_id"`
	CreatedAt           time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt           time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName BotDraft's table name
func (*BotDraft) TableName() string {
	return TableNameBotDraft
}
