// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBot = "bots"

// Bot mapped from table <bots>
type Bot struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Tab           string    `gorm:"column:tab" json:"tab"`
	CreatorID     int64     `gorm:"column:creator_id" json:"creator_id"`
	CreatorName   string    `gorm:"column:creator_name" json:"creator_name"`
	CreatorPic    string    `gorm:"column:creator_pic" json:"creator_pic"`
	Status        int32     `gorm:"column:status;comment:1-default 2-publish 3-delete" json:"status"` // 1-default 2-publish 3-delete
	Name          string    `gorm:"column:name;not null" json:"name"`
	Description   string    `gorm:"column:description" json:"description"`
	Image         string    `gorm:"column:image" json:"image"`
	Users         int32     `gorm:"column:users" json:"users"`
	Conversations int32     `gorm:"column:conversations" json:"conversations"`
	PickType      int32     `gorm:"column:pick_type;comment:1- pick, 0-default" json:"pick_type"` // 1- pick, 0-default
	Config        string    `gorm:"column:config" json:"config"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Bot's table name
func (*Bot) TableName() string {
	return TableNameBot
}
