// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameConversation = "conversations"

// Conversation mapped from table <conversations>
type Conversation struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type      int32     `gorm:"column:type;not null;default:1;comment:1-normal 2-draft" json:"type"` // 1-normal 2-draft
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	BotID     int64     `gorm:"column:bot_id;not null" json:"bot_id"`
	Title     string    `gorm:"column:title" json:"title"`
	Status    int32     `gorm:"column:status;default:1" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Conversation's table name
func (*Conversation) TableName() string {
	return TableNameConversation
}
