// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID          int64     `gorm:"column:user_id" json:"user_id"`
	BotID           int64     `gorm:"column:bot_id" json:"bot_id"`
	ConversationID  int64     `gorm:"column:conversation_id;not null" json:"conversation_id"`
	MessageType     string    `gorm:"column:message_type;not null" json:"message_type"`
	Content         string    `gorm:"column:content" json:"content"`
	ToolCallID      string    `gorm:"column:tool_call_id" json:"tool_call_id"`
	ToolCall        string    `gorm:"column:tool_call" json:"tool_call"`
	BackendToolCall string    `gorm:"column:backend_tool_call" json:"backend_tool_call"`
	NextMsgIds      string    `gorm:"column:next_msg_ids" json:"next_msg_ids"`
	Status          int32     `gorm:"column:status;not null;comment:0-default 1-success 2-fail" json:"status"` // 0-default 1-success 2-fail
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
