// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMethod = "methods"

// Method mapped from table <methods>
type Method struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PluginID        int64     `gorm:"column:plugin_id;not null" json:"plugin_id"`
	Name            string    `gorm:"column:name;not null" json:"name"`
	Description     string    `gorm:"column:description" json:"description"`
	HTTPSubPath     string    `gorm:"column:http_sub_path" json:"http_sub_path"`
	HTTPMethod      string    `gorm:"column:http_method" json:"http_method"`
	ContractAddress string    `gorm:"column:contract_address" json:"contract_address"`
	ContractAbi     string    `gorm:"column:contract_abi" json:"contract_abi"`
	MethodCallName  string    `gorm:"column:method_call_name" json:"method_call_name"`
	InputSchema     string    `gorm:"column:input_schema" json:"input_schema"`
	InputExample    string    `gorm:"column:input_example" json:"input_example"`
	OutputSchema    string    `gorm:"column:output_schema" json:"output_schema"`
	OutputExample   string    `gorm:"column:output_example" json:"output_example"`
	Status          int32     `gorm:"column:status;not null;default:1;comment:1-publish, 2-unpublish, 3-delete" json:"status"` // 1-publish, 2-unpublish, 3-delete
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Method's table name
func (*Method) TableName() string {
	return TableNameMethod
}
