// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePlugin = "plugins"

// Plugin mapped from table <plugins>
type Plugin struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatorID   int32     `gorm:"column:creator_id" json:"creator_id"`
	CreatorName string    `gorm:"column:creator_name" json:"creator_name"`
	CreatorPic  string    `gorm:"column:creator_pic" json:"creator_pic"`
	Tab         string    `gorm:"column:tab" json:"tab"`
	Bots        int32     `gorm:"column:bots" json:"bots"`
	PluginKey   string    `gorm:"column:plugin_key" json:"plugin_key"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Description string    `gorm:"column:description" json:"description"`
	ImageURL    string    `gorm:"column:image_url" json:"image_url"`
	Status      int32     `gorm:"column:status;not null;default:1;comment:1-defalut, 2-publish, 3-delete" json:"status"` // 1-defalut, 2-publish, 3-delete
	PluginType  string    `gorm:"column:plugin_type;not null" json:"plugin_type"`
	HTTPPath    string    `gorm:"column:http_path" json:"http_path"`
	Headers     string    `gorm:"column:headers" json:"headers"`
	AuthInfo    string    `gorm:"column:auth_info" json:"auth_info"`
	Config      string    `gorm:"column:config" json:"config"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Plugin's table name
func (*Plugin) TableName() string {
	return TableNamePlugin
}
